# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deployment

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      
      - name: Fetch Tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 8
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn test

      - name: echo
        run: |
          git describe --tags

      - name: Patch version
        run: |
          TAG=$(git describe --tags)
          echo Deploy version $TAG
          git config --global user.name "chgohlke"
          git config --global user.email "christian.gohlke@spring-media.de"
          git remote add publisher "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          npm version $TAG -m "Automatically updated npm version to %s"
          git push publisher HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
